### ISSUE TITLE
parse json for script.R

### ISSUE THREAD

**Issue by np-completed** [lorindavies/R_Downloadtoolkit_CSSEGISandData#1]
parse json for data with regular updates (semi real time).  I do not have permission to submit a pull request so I created a fork. See my 'script.R' file to see changes I made from your file: https://github.com/prfrl/R_Downloadtoolkit_CSSEGISandData/blob/master/script.R

`# this commented out line is live data - only I haven't worked out how to use it yet - anyone familiar with loading this into a decent format welcome to help out!`
`# ffg<- read_file("https://covid19-report.today/api/latest-report")`

library(jsonlite)
ffg <- fromJSON("https://covid19-report.today/api/latest-report/")

 
ffg.new <- as_tibble(ffg$report[2:nrow(ffg$report),], .name_repair= ~ffg$report[1,])
ffg.new 

ffg_totals <- as_tibble(t(ffg$totals[2,]), .name_repair= ~ffg$totals[1,])
ffg_totals 

ffg_last_update <- lubridate::as_datetime(ffg$lastUpdateTimestamp/1000, tz='UTC' )
`# not sure about the time zone, the web content did not appear to list a time zone`
ffg_last_update

**Comment by lorindavies** [comment]
merged those changes into the script. Thanks for the contribution
